# default group
server 172.21.100.100 -g global

# fallback group
server 1.1.1.1 -e -g fallback
server 1.0.0.1 -e -g fallback

# cn group
server 114.114.114.114 -e -g domestic
server 180.76.76.76 -e -g domestic
server 223.5.5.5 -e -g domestic
