# disable HTTPS
force-qtype-SOA 65

# bind
bind [::]:53
bind-tcp [::]:53

log-level info

# dns cache
cache-persist yes
cache-file /etc/smartdns/smartdns.cache
cache-checkpoint-time 43200

# dns prefetch
prefetch-domain yes
serve-expired yes
serve-expired-prefetch-time 21600

# dual stack
# dualstack-ip-selection yes

# TODO: dns 64
# dns64 64:ff9b::/96

# server groups

conf-file server-list.conf

# client rules
# conf-file client.conf

# special rules
# conf-file special.conf

# address rules
# conf-file address.conf

# domain rules
# conf-file domain.conf
