name: realmp-ingress
services:
  realmp-ingress:
    image: ghcr.nju.edu.cn/se1jaku/realmp:latest
    hostname: realmp-ingress
    container_name: realmp-ingress
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    networks:
      - realmp-ep1
      - realmp-ep2
    cap_add:
      - NET_ADMIN
    environment:
      - MPTCP_DIRECTION=out
    ports:
      # NOTE: predefined port range for relay, make sure to update the config.toml accordingly
      - 20000-21000:20000-21000
    volumes:
      - ${REALMP_CONFIG_DIR:-/etc/realmp}:/etc/realm
    command: -c /etc/realm/ingress.toml

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${REALMP_MEM_LIMIT:-128}mb

networks:
  realmp-ep1:
    name: realmp-ep1
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  realmp-ep2:
    name: realmp-ep2
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
